### ISSUE TITLE
composer.json needs to require FosUserBundle

### ISSUE THREAD

**Issue by twencl** [aimeos/aimeos-symfony#13]
It appears as though this package expects FosUserBundle to be installed but doesn't require it via composer.json.

Ex:
```
vagrant@dev:/var/www/sms_new_site/current$ php app/console aimeos:setup
PHP Fatal error:  Class 'FOS\UserBundle\Model\User' not found in /var/www/sms_new_site/current/vendor/aimeos/aimeos-symfony2/Entity/FosUser.php on line 22
```

**Comment by aimeos** [comment]
The FOS UserBundle is only in the "require-dev" section. We will see if we can make it truly optional or if we have to add it to the "require" section in the composer.json file.

**Comment by aimeos** [comment]
We did some tests with Symfony 3 and noticed that it doesn't work without the development packages: https://github.com/symfony/symfony/issues/17308

How did you do your setup?

**Comment by aimeos** [comment]
We did some tests and now we've added the FOS user bundle as general requirement.

Unfortunately, it doesn't work without even you have the choice not to use it. The cache warmup in production mode will fail because the annotations in the FOSUser entity will be evaluated while the implemented FOS user model interface is missing.

Could you please check if it works now for you? Please use version "1.2.x-dev" in composer.json. I had to execute ```rm -rf ./app/cache``` to get rid of a nasty error due to caching (cache:clear doesn't work).

**Comment by twencl** [comment]
I have a string of meetings coming up but will test this change later today. Thanks for the quick response.

**Comment by aimeos** [comment]
@twencl Any news on this?
